Repository SierraSystems/jag-pcss-criminal, pull requests merged in 2021-10, with the labels that each got.

#3 WSDL
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/configuration/SoapConfig.java
  pcss-criminal-application/src/main/resources/xsdSchemas/pcssCriminalW.wsdl
Labels: FIRST

#4 pull request template
  .github/pull_request_template.md
Labels: invalid

#16 exclude patterns
  .codeclimate.yml
Labels: bug

#17 Fix test
  pcss-criminal-common/src/test/java/ca/bc/gov/open/pcsscriminalcommon/serializer/InstantDeserializerTest.java
Labels: porkchopsandwiches
